//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROUTEJOBS1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public System.DateTime DateJob { get; set; }
        public string DestinationID { get; set; }
        public string WarehouseID { get; set; }
    
        public virtual DESTINATION DESTINATION { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
